- hosts: localhost
  pre_tasks:
  - name: Update Apt
    become: true
    apt:
      force_apt_get: true
      update_cache: true
      state: present
    tags:
      - install
      - core
  tasks:
    - include: tasks/git-setup.yml
    - include: tasks/brave.yml
    - include: tasks/nvim-setup.yml
